### ISSUE TITLE
你好，3.0的版本去除了PCM数据吗？

### ISSUE THREAD

**Issue by Veryed-VS** [ywl5320/wlmedia#51]
你好，请问3.0的版本去除了PCM数据吗？我们使用了你的库实现了获取音频播放实时获取PCM数据，效果不错。现在发现3.0版本去除，请问后续还会加回来吗？

**Comment by wanliyang1990** [comment]
你好，内部有的，只是没有回调到应用层，给ywl5320@163.com发邮件，会给你有pcm回调的包

**Comment by Veryed-VS** [comment]
你好，请问是否会考虑在这个库加回去。也许这样直接导入会跟舒服一些。应该对整个库或者应用层来说，没有任何影响。也许对其他人也有用到。

**Comment by wanliyang1990** [comment]
好的，周末就加回去

**Comment by Veryed-VS** [comment]
喔。你这个作者和分享精神实在太棒了。
刚刚才看到你还开源了一个wlmusic的库，这个是只针对音频播放的吗？或者这个更适合我，因为我这边直播放音频文件的，也有PCM数据。但是发现已经6年没更新了？我看star也不算少，请问这个库是否会考虑继续维护？

**Comment by wanliyang1990** [comment]
这个库目前没有维护了哈，推荐使用当前这个库

**Comment by Veryed-VS** [comment]
好的好的。感谢你的解答。

**Comment by wanliyang1990** [comment]
支持pcm回调版本 邮箱已发给你了 你这边测一下呢

**Comment by Veryed-VS** [comment]
你好。找了一圈，没有发现呢？麻烦请看一下邮箱是否发送成功呢。

**Comment by wanliyang1990** [comment]
昨天就发给你了 你查看一下呢

**Comment by wanliyang1990** [comment]
链接: https://pan.baidu.com/s/1NzEmxnG6-QL2oBFfZsp0_Q 提取码: b8n5

**Comment by Veryed-VS** [comment]
收到。十分感谢！

**Comment by ywl5320** [comment]
新版本已跟新，回到2.0水印方式，音频播放无限制，你可以再试试。
