### ISSUE TITLE
请问，如何添加请求头

### ISSUE THREAD

**Issue by coderZy2015** [ywl5320/wlmedia#52]
访问防盗链资源需要验证一下，没找到加请求头的方法。

**Comment by wanliyang1990** [comment]
你好，可以使用setOptions设置请求头，使用3.0.0版本测试，3.0.1有个bug，下个版本跟新就修复。

**Comment by ywl5320** [comment]
你好，新版本已更新，添加头信息方式如下：wlPlayer.setOptions("headers", "Referer: xxxx");
